### ISSUE TITLE
Postgres user being passed as Postgress database

### ISSUE THREAD

**Issue by AndresPineros** [safesoftware/helm-charts#54]
Chart: safesoftware/fmeserver-2019.1.1
Version: 0.2.5
Pod: core-0 (statefulset)
Container: core

---------

In the Core container, the variable PGSQLUSERNAME is actually being used as the database name instead of the PGSQLDATABASENAME variable.

The default variables work because the "fmeserver.database.name" is equal to "fmeserver.database.user" with a value of "fmeserver". I'm using a database outside of the cluster, as recommended by the docs, and I'm getting an error saying the database doesn't exist, but it is showing me the name of the username.

I modified the name of my user to match the name of my database, and things worked. I think it is a mistake somewhere in the container passing variables to the process, or an issue inside Core when reading the envVars and forming the connection string.

Sorry I'm not showing any logs, I already fixed the issue and can't break it for it to happen again.

**Comment by AndresPineros** [comment]
This is my first time using `psql`, if I had to guess, the issue is happening here:
```
until PGPASSWORD=${PGSQLPASSWORD} psql -h ${PGSQLHOSTNAME} -p ${PGSQLPORT} -c "SELECT EXISTS(SELECT * FROM information_schema.tables WHERE table_name = 'fme_config_props')" -w
 -t -U ${PGSQLUSERNAME} | grep t
```
Because psql is weird like that, or somewhere in the variable assignment.

**Comment by garnold54** [comment]
Thanks for the report! I have repro'd it and I will take a look at why this is happening,

**Comment by garnold54** [comment]
Apologies for not updating this issue before! This was fixed in FME 2020 and later.
