### ISSUE TITLE
Chart version fmeserver-2021.2.6

### ISSUE THREAD

**Issue by bartzwemmer** [safesoftware/helm-charts#84]
I see there are Docker images version fmeserver-2021.2.6. Are there plans for releasing a Helm chart with this version?

**Comment by garnold54** [comment]
Yes, we have actually tightened up our versioning of the helm charts to just be versioned on the major release, so you can use the helm chart version `fmeserver-2021.2-0.2.36`.

You can install using that tag using a command similar to:
`helm install fmeserver safesoftware/fmeserver-2021.2 --set fmeserver.image.tag=2021.2.6`

See the readme here: https://github.com/safesoftware/helm-charts/blob/master/readme-archive/README-2021.2.md for details

**Comment by bartzwemmer** [comment]
Thanks for the answer. I think I overlooked that flag.
