### ISSUE TITLE
Chart names don't conform to Helm best practices

### ISSUE THREAD

**Issue by jsw1993** [safesoftware/helm-charts#89]
Hi.

All the FME Helm charts names contain dots.

As per the below link, Helm published best practices state 

> Dots should not be used in chart names.

https://helm.sh/docs/chart_best_practices/conventions/#chart-names

This also causes issues if trying to deploy the FME Helm charts using a CI/CD tool such as Flux.

Can chart naming be changed to conform with Helm best practice?

**Comment by om2468** [comment]
Also mentioned in a community post here: [community post link](https://community.safe.com/s/question/0D5Dm00000AN4i1KAD/fme-server-deployment-in-aks-flux-wont-deploy-it-as-the-naming-of-the-helm-chart-isnt-in-line-with-helm-best-practices
)

**Comment by garnold54** [comment]
Sorry for the delay in responding to this. We released updated versions of our 2022.2 and 2023.0 charts with dashes instead of dots in the name. The chart names should be `fmeserver-2022-2` and `fmeserver-2023-0`.

Let me know if that doesn't solve your issue!

**Comment by jsw1993** [comment]
Many thanks
