### ISSUE TITLE
Duplicate Ingress Annotation

### ISSUE THREAD

**Issue by jsw1993** [safesoftware/helm-charts#91]
Hi.

The values file for the 2023 chart has duplicate annotations for the web ingress.

The `nginx.ingress.kubernetes.io/proxy-body-size` annotation is specified in the values file on [line 83](https://github.com/safesoftware/helm-charts/blob/master/chart-source/fmeserver-2023.0/values.yaml#L83) and line [91](https://github.com/safesoftware/helm-charts/blob/master/chart-source/fmeserver-2023.0/values.yaml#L91)

This means the chart doesn't validate for deployment using Flux. I'd suggest the one on line 91 is removed.

Flux issue referenced here: https://github.com/fluxcd/helm-controller/issues/283

Many thanks

**Comment by garnold54** [comment]
Thanks! I have submitted a fix internally. I'm going to be away on vacation until next week, but I will get that fix into this public repo when I am back and will update you here.

**Comment by jsw1993** [comment]
Brill, many thanks.

**Comment by garnold54** [comment]
Thanks for your patience! Version `0.2.61` of the `fmeserver-2023-0` chart should have this fix in it.

**Comment by jsw1993** [comment]
Absolute hero. Is deploying perfectly with flux. Many thanks.
