### ISSUE TITLE
Deprecated JDK option for start of tomcat (web container)

### ISSUE THREAD

**Issue by TinoM** [safesoftware/helm-charts#95]
With FME Flow 2023 and newer the helmcharts file core-statefulset.yaml defines:
```
            {{- if .Values.resources.web.limits.memory }}
            - name: USE_CGROUP_MEMORY_FOR_HEAP
              value: "true"
            {{- end }}
```
If a memory limit is defined, this leads the start_tomcat file.sh in the web image to set some experimental flags:
```
#!/bin/bash
# wait until this directory exists. The services won't work if the logging files aren't there yet
while [ ! -d /data/fmeserverdata/localization ]
do
    sleep 1
done

if [ "$USE_CGROUP_MEMORY_FOR_HEAP" = true ] ; then
    JAVA_OPTS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2 -XX:+ExitOnOutOfMemoryError -XX:+PrintFlagsFinal" catalina.sh run
else
    catalina.sh run
fi
```
JDK11 deprecated and removed `UseCGroupMemoryLimitForHeap`.
Container awareness is now done with `UseContainerSupport`, which is enabled by default. At least as far as i understand https://developers.redhat.com/articles/2022/04/19/java-17-whats-new-openjdks-container-awareness#

Could you give this a double check?

**Comment by garnold54** [comment]
Thanks! I will take a look and remove that setting from the chart.

**Comment by TinoM** [comment]
Thank you @garnold54 !

The memory usage/handling of JDK17(2023.1) seems vastly different compared to JDK8 (2022.2.8.).
In this specific project we are required to set memory request limits for each pod and after monitoring we have been running 202.2.8 fine:
`resources:
  core:
    requests:
      memory: 1.5Gi
      cpu: 200m
    limits:
      memory: 3Gi`
This is the memory usage when doing a system backup on our 2022.2.8 instance:
![core_memory_2022_8](https://github.com/safesoftware/helm-charts/assets/3512161/e7f0e17d-a8cf-4a1c-908e-817415f87c36)
As you can see, when i started the backup at around 10:39, the memory usage increased a bit, but never exceeded 2GiB.

This is the 2023.1 instance:
![core_memory_2023_1](https://github.com/safesoftware/helm-charts/assets/3512161/1ea5015a-af63-4d12-ae1d-47189f6917aa)
When idling it was already hitting the 3GiB limit. To it's credit: It never exeeded the limit, so the Cluster never killed the pod.
It was not possible to create a system backup, it always crashed with a java exception in the Configuration component.

At ~10:38 you see, i increased the limits to:
`resources:
  core:
    requests:
      memory: 4Gi
      cpu: 200m
    limits:
      memory: 8Gi`
The backup process begins at ~10:39 and the memory usage shortly hits 5GiB.
This time, the backup was created without a crash.

Both environments are pretty identical in regard to user (~50), repos (~30), workspaces (~150), automations (~70).
Only the amount of data in SHARED_RES_DATA\data is very different.
The resulting backup files sizes related to the memory usage screenshots are:
- 2022.2.8 : 9,2GiB
- 2023.1: 1,2GiB

**Comment by rijagomo** [comment]
Hi @TinoM,

I ran through a test to see if the FME Flow 23.1 used more memory than 22.2, but it appeared to be the same. In both your test cases are you backing up to a resource location or are you downloading the backup to the browser? Can you do a comparison and backup to a resource folder? Additionally, it would be great if you can [create a case ](https://community.safe.com/s/submit-case)and we can continue to explore there.

**Comment by TinoM** [comment]
Hi @rijagomo ,

the backup is written to a ressource folder on both instances. Here are the graphs from the last 24h of both instances:
FME 2023.1 Build 23636:
![image](https://github.com/safesoftware/helm-charts/assets/3512161/91428986-95a9-4ed2-acd0-bf7161607ad5)
FME 2022.2.8 Build 22802:
![image](https://github.com/safesoftware/helm-charts/assets/3512161/7408a2f5-35e0-42c2-93cd-7323ba755786)

On both system at 5am a backup was written to shared_res/backup, resulting in a 1,33GiB file on the 2023 system and in a 11,56GiB on the 2022 system.
It was no problem for us to increase the memory limits, i was just wondering why the memory usage is higher. But of course i also increased the request memory value, so maybe its just java now using more memory for better performance. It's fine, no need for a bug report i think.

(Beside the initial problem of this bug report with the deprecated jdk options ;) )

**Comment by rijagomo** [comment]
Hi @TinoM,

I don't know why the web component is so high. On a non-Kubernetes linux deployment I am not seeing this bump when doing a backup. In 2023 we forced encryption all backups with the custom key, but again I am not seeing this memory usage you are.  If this becomes problem please make a case and we can help you explore your instance.

**Comment by TinoM** [comment]
Java options have been updated with the FME Flow 2024 Charts.
